// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GLogScrobbler {
    
    
    public partial class ChooseDeviceDialog {
        
        private Gtk.VBox upperBox;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label label1;
        
        private Gtk.ComboBox devicesBox;
        
        private Gtk.Expander expander;
        
        private Gtk.FileChooserWidget fileChooser;
        
        private Gtk.Label GtkLabel13;
        
        private Gtk.HSeparator hseparator1;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget GLogScrobbler.ChooseDeviceDialog
            this.Name = "GLogScrobbler.ChooseDeviceDialog";
            this.Title = Mono.Unix.Catalog.GetString("Choose Device");
            this.TypeHint = ((Gdk.WindowTypeHint)(1));
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.DefaultHeight = 53;
            this.SkipPagerHint = true;
            this.SkipTaskbarHint = true;
            this.HasSeparator = false;
            // Internal child GLogScrobbler.ChooseDeviceDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.upperBox = new Gtk.VBox();
            this.upperBox.Name = "upperBox";
            this.upperBox.Spacing = 6;
            this.upperBox.BorderWidth = ((uint)(5));
            // Container child upperBox.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("<big>Selected device</big>");
            this.label1.UseMarkup = true;
            this.hbox1.Add(this.label1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.label1]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.devicesBox = new Gtk.ComboBox();
            this.devicesBox.Name = "devicesBox";
            this.devicesBox.Active = 0;
            this.hbox1.Add(this.devicesBox);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.devicesBox]));
            w3.Position = 1;
            this.upperBox.Add(this.hbox1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.upperBox[this.hbox1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child upperBox.Gtk.Box+BoxChild
            this.expander = new Gtk.Expander(null);
            this.expander.CanFocus = true;
            this.expander.Name = "expander";
            // Container child expander.Gtk.Container+ContainerChild
            this.fileChooser = new Gtk.FileChooserWidget(((Gtk.FileChooserAction)(2)));
            this.fileChooser.WidthRequest = 500;
            this.fileChooser.HeightRequest = 300;
            this.fileChooser.Name = "fileChooser";
            this.expander.Add(this.fileChooser);
            this.GtkLabel13 = new Gtk.Label();
            this.GtkLabel13.Name = "GtkLabel13";
            this.GtkLabel13.LabelProp = Mono.Unix.Catalog.GetString("Browse for a mountpoint");
            this.GtkLabel13.UseMarkup = true;
            this.GtkLabel13.UseUnderline = true;
            this.expander.LabelWidget = this.GtkLabel13;
            this.upperBox.Add(this.expander);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.upperBox[this.expander]));
            w6.Position = 1;
            w1.Add(this.upperBox);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(w1[this.upperBox]));
            w7.Position = 0;
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.hseparator1 = new Gtk.HSeparator();
            this.hseparator1.Name = "hseparator1";
            w1.Add(this.hseparator1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(w1[this.hseparator1]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            // Internal child GLogScrobbler.ChooseDeviceDialog.ActionArea
            Gtk.HButtonBox w9 = this.ActionArea;
            w9.Name = "actionArea";
            w9.Spacing = 6;
            w9.BorderWidth = ((uint)(5));
            w9.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child actionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w10 = ((Gtk.ButtonBox.ButtonBoxChild)(w9[this.buttonCancel]));
            w10.Expand = false;
            w10.Fill = false;
            // Container child actionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.Sensitive = false;
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w11 = ((Gtk.ButtonBox.ButtonBoxChild)(w9[this.buttonOk]));
            w11.Position = 1;
            w11.Expand = false;
            w11.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 353;
            this.Show();
            this.Response += new Gtk.ResponseHandler(this.OnResponse);
            this.devicesBox.Changed += new System.EventHandler(this.OnDevicesBoxChanged);
            this.fileChooser.CurrentFolderChanged += new System.EventHandler(this.OnFileChooserCurrentFolderChanged);
        }
    }
}
